

#This is where a random 'Mystery Number' is generated by the program
number = rand(1..10)

#Introductions 
puts "Ladies and gentlemen, boys and girls of all ages, step right up and guess the MYSTERY NUMBER!\nYou may call me Le Grand David. I will be the Game Master.\nYou have three chances to guess the Mystery Number - it is between 0 and 10!"


puts "What's your name, friend?"
user_name = gets.chomp.capitalize

puts "OK, #{user_name}, let's get started. What's your first guess?"

attempts = 0

#Beginning of code block. Get user input and compare it to 'number' value. There are 3 options: Correct, too high, or too low. Different responses for each. 
loop do
  begin
    guess = gets.chomp.to_i
   
  
    if guess == number
      puts "Be ye psychic?? You, #{user_name}, guessed my number! It is, indeed, #{number}.\nWell done!"
      break

    
    elsif guess > number  
      puts "NEGATRON! Too high."
      attempts = attempts += 1
    else
      puts "NEGATRON! Too low."
      attempts = attempts += 1
	end
end

#User attempted more than 3 guess, which results in a unique response and the end of the game. 
if attempts > 2
	print "ARGH! Le Grand David has vanquished his foe once again! You didn't guess the Mystery Number!\nGAME OVER"
	break
end
end


